### ISSUE TITLE
Flags: 0x800000

### ISSUE THREAD

**Issue by foxt** [matteyeux/iOS-Utilities#5]
```js
Vulpes:iOS-Utilities thelmgn$ cat ../payload | ./pbzx > a
Flags: 0x800000
Vulpes:iOS-Utilities thelmgn$ cat a
Vulpes:iOS-Utilities thelmgn$ 
```

what does this mean lol

**Comment by matteyeux** [comment]
This just a mirror repo (which is not up to date) open an issue on newosxbook.com.

I'll delete this repo soon, as I don't maintain it anymore.

**Comment by foxt** [comment]
is there a link to this new repo? @matteyeux 

**edit** found it http://newosxbook.com/articles/OTA3.html

**edit2**: same error

**edit3** seems to be an :watch:os5 thing

**edit4**: downloaded and extracted watchOS4, now ota isn't playing, it lists the files but no extraction

it'd also be neat to specify this in the readme
